//ERRORS
export const FETCH_FAILED = 'FETCH_FAILED'
export const CLEAR_ERROR_STACK = 'CLEAR_ERROR_STACK';

// USER AUTH
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_REGISTER_START = 'USER_REGISTER_START';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

//CHANNELS
export const FETCH_ALL_CHANNELS_SUCCESS = 'FETCH_ALL_CHANNELS_SUCCESS';
export const FETCH_OWN_CHANNELS_SUCCESS = 'FETCH_OWN_CHANNELS_SUCCESS';
export const FETCH_SUBSCRIBED_CHANNELS_SUCCESS = 'FETCH_SUBSCRIBED_CHANNELS_SUCCESS';

//CHANNELS POSTS
export const LOAD_CHANNELS_POSTS_START = 'LOAD_CHANNELS_POSTS_START';
export const LOAD_CHANNELS_POSTS_SUCCESS = 'LOAD_CHANNELS_POSTS_SUCCESS';

//FEED
export const FETCH_FEED_START = 'LOAD_OWN_CHANNELS_START';
export const FETCH_FEED_SUCCESS = 'LOAD_OWN_CHANNELS_SUCCESS';