export const FETCH_FAILED = 'FETCH_FAILED'
export const CLEAR_ERROR_STACK = 'CLEAR_ERROR_STACK';

// USER AUTH
export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_REGISTER_START = 'USER_REGISTER_START';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

//CHANNELS
export const LOAD_OWN_CHANNELS_START = 'LOAD_OWN_CHANNELS_START';
export const LOAD_OWN_CHANNELS_SUCCESS = 'LOAD_OWN_CHANNELS_SUCCESS';
export const LOAD_SUBSCRIBED_CHANNELS_START = 'LOAD_SUBSCRIBED_CHANNELS_START';
export const LOAD_SUBSCRIBED_CHANNELS_SUCCESS = 'LOAD_SUBSCRIBED_CHANNELS_SUCCESS';

export const LOAD_CHANNELS_POSTS_START = 'LOAD_CHANNELS_POSTS_START';
export const LOAD_CHANNELS_POSTS_SUCCESS = 'LOAD_CHANNELS_POSTS_SUCCESS';
