export const FETCH_FAILED = 'FETCH_FAILED'
export const CLEAR_ERROR_STACK = 'CLEAR_ERROR_STACK';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_REGISTER_START = 'USER_REGISTER_START';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const CREATE_CLUB_START = 'USER_REGISTER_START';
export const CREATE_CLUB_SUCCESS = 'USER_REGISTER_SUCCESS';

export const LOAD_CLUB_POSTS_START = 'USER_REGISTER_START';
export const LOAD_CLUB_POSTS_SUCCESS = 'USER_REGISTER_SUCCESS';

export const ADD_POST = 'ADD_POST';